### ISSUE TITLE
Make use of the params keyword

### ISSUE THREAD

**Issue by stefankip** [skttl/Our.Umbraco.FullTextSearch#15]
You can use the `params` keyword (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params) instead of the string[] params for defining multiple title and summary properties.

Current situation: `public Search AddTitleProperties(string[] aliases)`
New situation: `public Search AddTitleProperties(params string[] aliases)`

Then you're able to call it like this: `.AddTitleProperties("prop1", "prop2", "prop3")`

**Comment by skttl** [comment]
Nice, didn't know that!
