### ISSUE TITLE
Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

### ISSUE THREAD

**Issue by stefankip** [skttl/Our.Umbraco.FullTextSearch#16]
There is a bug on this line:
https://github.com/skttl/Our.Umbraco.FullTextSearch/blob/417b360f265c6812ce9a3f4321b49f3ca32675d3/src/Our.Umbraco.FullTextSearch/Services/SearchService.cs#L252

The index `{4}` doesn't exist, should by `{3}` I guess. Maybe use [string interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/string-interpolation) instead?

**Comment by skttl** [comment]
I think string interpolation would be better for readability. Can you update your PR?
