### ISSUE TITLE
No results when no specific culture is used

### ISSUE THREAD

**Issue by stefankip** [skttl/Our.Umbraco.FullTextSearch#17]
When no specific culture is used in the umbraco environment and no specific culture is specified with the `SetCulture` method, no results are returned.

The issue is in this line:
https://github.com/skttl/Our.Umbraco.FullTextSearch/blob/417b360f265c6812ce9a3f4321b49f3ca32675d3/src/Our.Umbraco.FullTextSearch/Services/SearchService.cs#L151
`__Published_{_search.Culture}:y`

In my index, there's only a non-culture published property:
`__Published:y`

**Comment by skttl** [comment]
We need to make this work for both variant and non-variant content. IIRC __Published (without the culture flag) is also present on variant nodes, which might cause problems if we were to change the query to `... AND (__Published_{search.Culture}:y OR __Published:y)`

What do you think?

**Comment by stefankip** [comment]
Yes it's present besides the culture-agnostic published properties.
I'm not sure the ultimate fix would be TBH.

**Comment by stefankip** [comment]
Hmm there is already a field called `__VariesByCulture` :-)

**Comment by stefankip** [comment]
Duplicate of #4
