### ISSUE TITLE
Search returns 0 result with culture set

### ISSUE THREAD

**Issue by aguyfromdenmark** [skttl/Our.Umbraco.FullTextSearch#24]
Search using `.SetCulture(model.Content.GetCultureFromDomains().ToLower())` return 0 results. 
Search without setting culture returns the expected amount of results. 

Site is set to "da-dk" in Umbraco, and that is also returned and passed to `SetCulture()`.

- Umbraco 8.5.5
- Package v. 0.2.0

**Comment by skttl** [comment]
This a duplicate of #4, but the issue hasn't been fixed completely.
