### ISSUE TITLE
Adding a doctype to DisallowedContentTypeAliases doesn't remove already indexed pages

### ISSUE THREAD

**Issue by skttl** [skttl/Our.Umbraco.FullTextSearch#29]
Just tried adding a doctype alias to that setting, and it didn't remove already indexed nodes of that type afterwards.

Rebuilding the examine index from Examine Dashboard didn't either, nor clicking Reindex on the Full Text Search dashboard.

We probably need to do some cleaning on this, and I would like suggestions. Here are my possible solutions:

**Search for existing nodes, and remove them on startup**
Since the settings change triggers a restart, we could have the site perform a search for all full text indexed nodes of the removed types, and remove those found.

**Add conditions to the search queries, to filter out excluded node types**
Let them be indexed, but filter them away, when searching.

**Regular cleanup job, like the one proposed on startup**
Just like the caching service runs every X seconds (don't remember), have it check for indexed nodes of disallowed types and remove those.

@stefankip or other, any thoughts?

**Comment by stefankip** [comment]
**Add conditions to the search queries, to filter out excluded node types**
The downside is that the pages get indexed. I have these system pages (404, 500) which return the HTTP status by design, but this gives errors in the logs.
