### ISSUE TITLE
No results returned if you do not have "Allow varying by culture" set to true on document type.

### ISSUE THREAD

**Issue by jt3432** [skttl/Our.Umbraco.FullTextSearch#4]
I think I may have found a "feature" with the plugin. If you do not have "Allow varying by culture" set to true on document types no results are ever returned. Line 151 of the SearchService.cs forces that the culture is appended to the __Pulished field name, i.e.  __Pulished_en_us. If "Allow varying by culture" is not true then culture specific fields are included in the indexed. If I am correct I think that adding an OR clause to line 151 would solve the issue. Updated line below. I am posting this as a question instead of a pull request just in case I am missing something and/or this is the intended behavior.

query.Append($" AND (_IndexType:content AND (_Published:y OR __Published_{_search.Culture}:y))");

**Comment by Sibren** [comment]
Thanks, this costed quite some searching, seems like a PR is in place. :-)

**Comment by skttl** [comment]
Thanks, I was aware that there might be some problems with non-varying content, just hasn't been a priority yet. I'll do the update and test for the next version :)
