### ISSUE TITLE
Absolute "for dummies" guide needed

### ISSUE THREAD

**Issue by claushingebjerg** [skttl/Our.Umbraco.FullTextSearch#6]
When i saw this package on our it made my day. I loved the original package, and was in need of a nice and easy to implement search solution for v8. And this looked great. And it says on the github page "Easy to set up"... :). Well it's not plug and play, thats for sure :). I'm stuck and really need som guidance. The entire Controller thing is a bit above my front end skills. But let me walk through my steps so far.

1. I installed the package from within Umbraco, after downloading the zip from Our - Succes

2. I set an app setting in the web config, like this

![Skærmbillede 2020-01-13 kl  13 09 26](https://user-images.githubusercontent.com/1854789/72255029-f4eb0200-3605-11ea-90ca-df19d94ef502.png)

3. i set all doc types to "Allow varying by culture"

4. i checked that there is content in the fullTextSearch fields in the External index. There is
![Skærmbillede 2020-01-13 kl  13 13 41](https://user-images.githubusercontent.com/1854789/72255464-17314f80-3607-11ea-97f4-8fdbc4394d71.png)

5. I created an "App_Code" folder. My site didn't have one.

6. Now things are getting into unknown territory. I created "MyProject.cshtml" in the App_Code folder and copy pasted from the dev docs.
![Skærmbillede 2020-01-13 kl  13 18 53](https://user-images.githubusercontent.com/1854789/72255551-4cd63880-3607-11ea-98bb-845ae810e8fd.png)

7. i created a partial for the search result and copy pasted from the dev docs.
![Skærmbillede 2020-01-13 kl  13 20 16](https://user-images.githubusercontent.com/1854789/72255615-7a22e680-3607-11ea-99cc-c3f1c86da39e.png)

8. when hitting the search page i get the following error:
![Skærmbillede 2020-01-13 kl  13 21 19](https://user-images.githubusercontent.com/1854789/72255666-9c1c6900-3607-11ea-8fd4-8c5136a73050.png)

**Comment by skttl** [comment]
I @claushingebjerg 

Thanks for reaching out :)

In your controller you put your search model in the `ViewBag`, so in your view, in stead of writing `Model.FullTextSearch...` you need to write `ViewBag.FullTextSearchResult`.

Let me know if that helps you :)
