### ISSUE TITLE
Filter out protected content (based on current member)

### ISSUE THREAD

**Issue by TimGeyssens** [skttl/Our.Umbraco.FullTextSearch#7]
Hey, first of all, great package and super docs!

But what I can't be able to find is how you can setup so it takes the protected pages and member access in account? Since I don't want an anonymous visitor finding intranet pages...

Cheers,
Tim

**Comment by skttl** [comment]
That would be good yes :)

How does the default examine implementation handle this? Can protected pages be filtered while searching?

**Comment by TimGeyssens** [comment]
Hey, well it isn't part of the index... It is defined in the examine index config ( support protected) so by default the external allows this ... So this will need to be handled by filtering the results...based on logged in member ( groups) and protected info of content doc...

**Comment by TimGeyssens** [comment]
Been looking a bit yesterday but first need to find out how I can get access to logged in member....

**Comment by skttl** [comment]
Hi @TimGeyssens 

Just looking around the old issues. The Full Text searching is based on the default ExternalIndex in Umbraco, so you either have to disable protected pages there, or do your own handling when searching.
