### ISSUE TITLE
Reindex all nodes on Save/Publish

### ISSUE THREAD

**Issue by Seaney01** [skttl/Our.Umbraco.FullTextSearch#9]
Having issues setting with the Reindex all nodes triggering on save/publish of content. 

Is there something that needs to be set up?

**Comment by Seaney01** [comment]
If it helps I keep getting this error in the logs after save/publish a content node.

Error in FullTextSearch retrieval.","@l":"Error","@x":"System.Net.WebException: The remote server returned an error: (404) Not Found.\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   at Our.Umbraco.FullTextSearch.Services.HtmlService.GetHtmlByUrl(String url, String& fullHtml)","SourceContext":"Our.Umbraco.FullTextSearch.Services.HtmlService","ProcessId":25244,"ProcessName":"w3wp","ThreadId":230,"AppDomainId":51,"AppDomainAppId":"LMW3SVC6ROOT","MachineName":"TARAHUMARA","Log4NetLevel":"ERROR"}

**Comment by skttl** [comment]
Do you have a host name set up for your site in Umbraco, and is the server able to load that url?

**Comment by Seaney01** [comment]
Forgot to check that. Had added it in previously but been removed after migrating to and from cloud. 

All working now. Thanks for your help.
